services:
  mock-server:
    build: .
    ports:
      - "4010:4010"
    environment:
      - HTTP_PORT=4010
      - MANIFEST_DIR=/app/manifests
      - AI_PROTOCOL_TAG=749cb825c99f03e9dc737294b41fd5f5552533b4
      - MANIFEST_SYNC_URL=https://raw.githubusercontent.com/ailib-official/ai-protocol/749cb825c99f03e9dc737294b41fd5f5552533b4/
      - RESPONSE_DELAY=0
      - ERROR_RATE=0
    volumes:
      - ./manifests:/app/manifests
